# Change these first
owner: clubon # Your GitHub organization or username, where this repository lives
repo: status.playreal.city # The name of this repository

sites:
  - name: playreal.com.tw
    url: https://playreal.com.tw/icont.ico
    icon: https://craft.playreal.city/bonbon.png
  - name: craft.playreal.city
    url: https://craft.playreal.city/bonbon.png
    icon: https://craft.playreal.city/bonbon.png
  - name: go.playreal.city
    url: https://go.playreal.city/bonbon.png
    icon: https://go.playreal.city/bonbon.png

status-website:
  theme: light

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.playreal.city
  # baseUrl: /your-repo-name
  favicon: https://craft.playreal.city/bonbon.png
  logoUrl: https://craft.playreal.city/bonbon.png
  name: Playreal
  introTitle: "**Playreal** System Status"
  introMessage: "[Playreal](https://playreal.com.tw) 實境遊戲引擎 | 打造無限想像，創造獨特體驗"
  scripts:
    - src: https://www.googletagmanager.com/gtag/js?id=G-MJ935RTNBM
      async: true

  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://playreal.com.tw

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
